services:
  app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    container_name: project-laravel-app
    volumes:
      - .:/workspaces/finalLaravelProject:cached
    working_dir: /workspace
    command: bash -lc "tail -f /dev/null"º
    environment:
      - TZ=UTC
    ports:
      - "8001:8000"
    depends_on:
      # Ahora depende de ambos servicios de base de datos
      - db
      - pgsql
      - redis
      - mailpit
      - libretranslate 

  # Servicio de MySQL
  db:
    image: mysql:8.4.3
    container_name: project-laravel-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: admin
    volumes:
      - dbdata-laravel11:/var/lib/mysql
    ports:
      - "3307:3306"

  # Servicio de PostgreSQL (Nuevo)
  pgsql:
    image: postgres:16-alpine
    container_name: project-laravel-pgsql
    restart: unless-stopped
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: admin
    volumes:
      - pgdata-laravel11:/var/lib/postgresql/data
    ports:
      - "5433:5432"
  # Servicio de Redis
  redis:
    image: redis:7
    container_name: project-laravel-redis
    ports:
      - "6379:6379"

  # Servicio de MailPit
  mailpit:
    image: axllent/mailpit:latest
    container_name: project-laravel-mailpit
    ports:
      - "8025:8025" # UI
      - "1025:1025" # SMTP

  # Servicio de LibreTranslate
  libretranslate:
    image: libretranslate/libretranslate
    container_name: project-laravel-libretranslate
    ports:
      - "5000:5000"
    environment:
      LT_API_KEY: ""  # puedes dejarlo vacío si no quieres usar autenticación
    restart: unless-stopped

volumes:
  dbdata-laravel11:
  # Nuevo volumen para PostgreSQL
  pgdata-laravel11: