display_errors=On
display_startup_errors=On
error_reporting=E_ALL
log_errors=On
# Tiempo máximo de ejecución para que no se te corten los procesos largos de Artisan
max_execution_time=600
max_input_time=600

memory_limit=1024M
post_max_size=64M
upload_max_filesize=64M
date.timezone=America/Bogota

; Opcache deshabilitado para desarrollo (Evita cache de código vivo)
opcache.enable=0
opcache.jit=0